name: emle-bespoke

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - pre_commit
  - versioneer
  - numpy
  - h5py
  - horton
  - cudatoolkit<11.9
  - openmm>=8.1
  - openmm-torch
  - openmm-ml
  - openmmforcefields
  - nnpops
  - pytorch
  - torchani
  - pip:
    - git+https://github.com/chemle/emle-engine.git
    - coloredlogs
